# Generated by Django 5.2.6 on 2025-11-12 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_interval', models.PositiveIntegerField(default=7, help_text='Days between reports')),
                ('report_time', models.TimeField(default='09:00:00', help_text='Time to generate report')),
                ('report_type', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], default='short', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_generation_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_report_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Progress Report Settings',
                'db_table': 'assistant_progress_report_settings',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField(help_text='Start of the reporting period')),
                ('period_end', models.DateTimeField(help_text='End of the reporting period')),
                ('progress_summary', models.TextField(blank=True, help_text='Overall progress towards fitness goals')),
                ('workout_feedback', models.TextField(blank=True, help_text='Workout consistency and performance feedback')),
                ('nutrition_feedback', models.TextField(blank=True, help_text='Nutrition adherence and quality feedback')),
                ('key_takeaways', models.TextField(blank=True, help_text='Main insights and action items')),
                ('report_type', models.CharField(default='short', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('generation_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assistant_progress_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='assistant_p_user_id_721cf0_idx'), models.Index(fields=['status', 'created_at'], name='assistant_p_status_0bb1fd_idx')],
            },
        ),
    ]
