# Generated by Django 5.2.6 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_progressreportsettings_progressreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreportsettings',
            name='report_time',
        ),
        migrations.AddField(
            model_name='progressreport',
            name='auto_generated',
            field=models.BooleanField(default=False, help_text='Was this report auto-generated?'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='nutrition_adherence',
            field=models.TextField(blank=True, help_text='Adherence rate analysis'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='nutrition_intake',
            field=models.TextField(blank=True, help_text='Average daily intake analysis'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='nutrition_recommendations',
            field=models.TextField(blank=True, help_text='Nutrition recommendations'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='workout_duration',
            field=models.TextField(blank=True, help_text='Average workout duration analysis'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='workout_frequency',
            field=models.TextField(blank=True, help_text='Workout frequency analysis'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='workout_recommendations',
            field=models.TextField(blank=True, help_text='Workout recommendations'),
        ),
    ]
