# Generated by Django 5.2.6 on 2025-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritionprofile_bmr_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serving',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serving',
            name='food',
        ),
        migrations.RemoveField(
            model_name='mealfoodentry',
            name='serving',
        ),
        migrations.AlterModelOptions(
            name='nutritionprofile',
            options={'verbose_name': 'Nutrition Profile', 'verbose_name_plural': 'Nutrition Profiles'},
        ),
        migrations.AddField(
            model_name='food',
            name='fatsecret_servings',
            field=models.JSONField(blank=True, default=list, help_text='Available serving options from FatSecret API'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_description',
            field=models.TextField(blank=True, help_text='Detailed description from FatSecret'),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='custom_serving_amount',
            field=models.FloatField(blank=True, help_text='Amount in the custom unit', null=True),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='custom_serving_unit',
            field=models.CharField(blank=True, help_text="Custom unit like 'grams', 'cups', 'pieces'", max_length=50),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='fatsecret_serving_id',
            field=models.CharField(blank=True, help_text='ID of the FatSecret serving from food.fatsecret_servings', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealfoodentry',
            name='serving_type',
            field=models.CharField(choices=[('fatsecret', 'FatSecret Predefined Serving'), ('custom', 'Custom Serving')], default='fatsecret', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='daily_calories_goal',
            field=models.PositiveIntegerField(default=2000, help_text='Calculated daily calorie target', verbose_name='Daily Calorie Goal'),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='daily_carbs_goal',
            field=models.FloatField(default=225.0, help_text='Calculated daily carbohydrate target in grams', verbose_name='Daily Carbs Goal (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='daily_fat_goal',
            field=models.FloatField(default=67.0, help_text='Calculated daily fat target in grams', verbose_name='Daily Fat Goal (g)'),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='daily_protein_goal',
            field=models.FloatField(default=125.0, help_text='Calculated daily protein target in grams', verbose_name='Daily Protein Goal (g)'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food_name'], name='nutrition_f_food_na_c4ba7b_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['brand_name'], name='nutrition_f_brand_n_f50385_idx'),
        ),
        migrations.AlterModelTable(
            name='food',
            table='nutrition_foods',
        ),
        migrations.AlterModelTable(
            name='mealfoodentry',
            table='meal_food_entries',
        ),
        migrations.AlterModelTable(
            name='nutritionprofile',
            table='nutrition_profiles',
        ),
        migrations.DeleteModel(
            name='Serving',
        ),
    ]
