# Generated by Django 5.2.6 on 2025-10-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_foodentry_fatsecret_serving_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprofile',
            name='bmi',
            field=models.FloatField(default=22.0, help_text='Calculated BMI based on current weight and height', verbose_name='Body Mass Index'),
        ),
    ]
