# Generated by Django 5.2.6 on 2025-10-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_nutritionprofile_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='custom_serving_unit',
            field=models.CharField(blank=True, help_text="Custom unit like 'grams', 'cups', 'pieces'", max_length=50, null=True),
        ),
    ]
