# Generated by Django 5.2.6 on 2025-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionprofile',
            name='bmr',
            field=models.FloatField(default=1600.0, help_text='Calculated BMR used for macro calculations', verbose_name='Basal Metabolic Rate'),
        ),
        migrations.AlterField(
            model_name='nutritionprofile',
            name='tdee',
            field=models.FloatField(default=2000.0, help_text='Calculated TDEE used for calorie goal', verbose_name='Total Daily Energy Expenditure'),
        ),
        migrations.AlterModelTable(
            name='dailyentry',
            table='nutrition_daily_entries',
        ),
        migrations.AlterModelTable(
            name='food',
            table='nutrition_food',
        ),
        migrations.AlterModelTable(
            name='meal',
            table='nutrition_meals',
        ),
        migrations.AlterModelTable(
            name='mealfoodentry',
            table='nutrition_meal_food_entries',
        ),
        migrations.AlterModelTable(
            name='serving',
            table='nutrition_servings',
        ),
    ]
