# Generated by Django 5.2.6 on 2025-09-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_serving_unique_together_remove_serving_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealfoodentry',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='mealfoodentry',
            name='food',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('serving_type', models.CharField(choices=[('fatsecret', 'FatSecret Predefined Serving'), ('custom', 'Custom Serving')], default='fatsecret', max_length=20)),
                ('fatsecret_serving_id', models.CharField(blank=True, help_text='Index/ID of the serving in food.fatsecret_servings array (0, 1, 2, etc.)', max_length=10, null=True)),
                ('custom_serving_unit', models.CharField(blank=True, help_text="Custom unit like 'grams', 'cups', 'pieces'", max_length=50)),
                ('custom_serving_amount', models.FloatField(blank=True, help_text='Amount in the custom unit', null=True)),
                ('quantity', models.FloatField(default=1.0, help_text='Number of servings consumed')),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='nutrition.dailyentry')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
            ],
            options={
                'verbose_name': 'Food Entry',
                'verbose_name_plural': 'Food Entries',
                'db_table': 'nutrition_food_entries',
                'ordering': ['daily_entry__date', 'meal_type', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealFoodEntry',
        ),
    ]
