# Generated by Django 5.2.6 on 2025-09-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_remove_mealfoodentry_meal_remove_mealfoodentry_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='fatsecret_serving_id',
            field=models.CharField(blank=True, help_text='Index/ID of the serving in food.fatsecret_servings array', max_length=10, null=True),
        ),
    ]
