# Generated by Django 5.2.6 on 2025-09-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_foodentry_fatsecret_serving_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
