# Generated by Django 5.2.6 on 2025-09-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_dailyentry_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='test',
        ),
    ]
