# Generated by Django 5.2.6 on 2025-10-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_dietplan_mealitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['diet_plan', 'meal_type', 'created_at'], 'verbose_name': 'Meal Item', 'verbose_name_plural': 'Meal Items'},
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='meal_plan',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='total_protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='custom_serving_amount',
            field=models.FloatField(blank=True, help_text='Amount in the custom unit', null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='custom_serving_unit',
            field=models.CharField(blank=True, help_text="Custom unit like 'grams', 'cups', 'pieces'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='fatsecret_serving_id',
            field=models.CharField(blank=True, help_text='Index/ID of the serving in food.fatsecret_servings array', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='is_alternative',
            field=models.BooleanField(default=False, help_text='Whether this is an alternative option'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for this meal item'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='quantity',
            field=models.FloatField(default=1.0, help_text='Number of servings planned'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='serving_type',
            field=models.CharField(choices=[('fatsecret', 'FatSecret Predefined Serving'), ('custom', 'Custom Serving')], default='fatsecret', max_length=20),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AlterModelTable(
            name='dietplan',
            table='nutrition_diet_plans',
        ),
        migrations.AlterModelTable(
            name='mealitem',
            table='nutrition_meal_items',
        ),
    ]
