# Generated by Django 5.2.6 on 2025-10-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_alter_dietplan_options_alter_mealitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='meal_plan',
        ),
        migrations.CreateModel(
            name='DietPlanFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Which meal this food belongs to', max_length=20)),
                ('serving_type', models.CharField(choices=[('fatsecret', 'FatSecret Predefined Serving'), ('custom', 'Custom Serving')], default='fatsecret', max_length=20)),
                ('fatsecret_serving_id', models.CharField(blank=True, help_text='Index/ID of the serving in food.fatsecret_servings array', max_length=10, null=True)),
                ('custom_serving_unit', models.CharField(blank=True, help_text="Custom unit like 'grams', 'cups', 'pieces'", max_length=50, null=True)),
                ('custom_serving_amount', models.FloatField(blank=True, help_text='Amount in the custom unit', null=True)),
                ('quantity', models.FloatField(default=1.0, help_text='Number of servings planned')),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of foods in the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan_foods', to='nutrition.dietplan')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_diet_plans', to='nutrition.food')),
            ],
            options={
                'verbose_name': 'Diet Plan Food',
                'verbose_name_plural': 'Diet Plan Foods',
                'db_table': 'nutrition_diet_plan_foods',
                'ordering': ['meal_type', 'order', 'created_at'],
                'unique_together': {('diet_plan', 'food', 'meal_type')},
            },
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
    ]
