# Generated by Django 5.2.5 on 2025-08-14 14:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, default=3, null=True)),
                ('reps', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('rest_time', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='template_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='workouts_ex_name_5d1c33_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle'], name='workouts_ex_muscle_405e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['difficulty'], name='workouts_ex_difficu_d7fa80_idx'),
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='workouts.template'),
        ),
        migrations.AlterUniqueTogether(
            name='templateexercise',
            unique_together={('template', 'exercise')},
        ),
    ]
