# Generated by Django 5.2.5 on 2025-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_templateexercise_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexercise',
            name='reps',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='rest_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
