# Generated by Django 5.2.5 on 2025-08-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_alter_templateexercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
