# Generated by Django 5.2.5 on 2025-08-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_templateexercise_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='isAlternative',
            field=models.BooleanField(default=False),
        ),
    ]
