# Generated by Django 5.2.6 on 2025-10-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_remove_templateexercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexercise',
            name='rest_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
