# Generated by Django 5.2.6 on 2025-11-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_templateexercise_rest_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_title', models.CharField(help_text='Title of the workout when it was performed', max_length=50)),
                ('started_at', models.DateTimeField(help_text='When the workout session started')),
                ('completed_at', models.DateTimeField(help_text='When the workout session was completed')),
                ('total_duration', models.DurationField(help_text='Total workout duration (completed_at - started_at)')),
                ('total_exercises', models.PositiveIntegerField(default=0, help_text='Total number of exercises performed')),
                ('total_sets', models.PositiveIntegerField(default=0, help_text='Total number of sets performed across all exercises')),
                ('workout_notes', models.TextField(blank=True, help_text='User notes about the completed workout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_template', models.ForeignKey(blank=True, help_text='Reference to the original template used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_history', to='workouts.template')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout History',
                'verbose_name_plural': 'Workout Histories',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateHistoryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='Exercise name when workout was performed', max_length=100)),
                ('performed_sets_data', models.JSONField(default=list, help_text="Actual sets performed: [{'reps': 12, 'weight': 50.5}, {'reps': 10, 'weight': 52.5}]")),
                ('total_sets_performed', models.PositiveIntegerField(default=0, help_text='Total number of sets performed for this exercise')),
                ('exercise_notes', models.TextField(blank=True, help_text='Notes specific to this exercise during the workout')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this exercise in the workout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to='workouts.exercise')),
                ('workout_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_exercises', to='workouts.templatehistory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('workout_history', 'exercise', 'order')},
            },
        ),
    ]
