# Generated by Django 5.2.6 on 2025-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_templatehistory_templatehistoryexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', help_text='Unit of measurement for weight values in sets_data', max_length=3),
        ),
        migrations.AddField(
            model_name='templatehistoryexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', help_text='Unit of measurement for weight values in performed_sets_data', max_length=3),
        ),
    ]
