# Generated by Django 5.2.6 on 2026-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_templateexercise_weight_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatehistoryexercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='set_type',
            field=models.CharField(choices=[('weight_reps', 'Weight & Reps'), ('reps_only', 'Reps Only'), ('duration', 'Duration')], default='weight_reps', help_text='Type of sets for this exercise', max_length=20),
        ),
        migrations.AddField(
            model_name='templatehistoryexercise',
            name='set_type',
            field=models.CharField(choices=[('weight_reps', 'Weight & Reps'), ('reps_only', 'Reps Only'), ('duration', 'Duration')], default='weight_reps', help_text='Type of sets performed for this exercise', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='sets_data',
            field=models.JSONField(blank=True, default=list, help_text='Array of objects containing set data based on set_type'),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', help_text='Unit of measurement for weight values (only for weight_reps type)', max_length=3),
        ),
        migrations.AlterField(
            model_name='templatehistoryexercise',
            name='performed_sets_data',
            field=models.JSONField(default=list, help_text='Actual sets performed based on set_type'),
        ),
        migrations.AlterField(
            model_name='templatehistoryexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')], default='kg', help_text='Unit of measurement for weight values (only for weight_reps type)', max_length=3),
        ),
    ]
