# Generated by Django 5.2.6 on 2026-01-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_alter_templatehistoryexercise_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateexercise',
            name='previous_sets_data',
            field=models.JSONField(blank=True, default=list, help_text='Last performed sets data from previous workout session'),
        ),
    ]
