# Generated by Django 5.2.4 on 2025-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='workout_frequency',
            field=models.CharField(choices=[('1_2', '1-2 Days'), ('3_4', '3-4 Days'), ('5_6', '5-6 Days')], default='3_4', verbose_name='Workout Frequency'),
        ),
        migrations.AddField(
            model_name='account',
            name='workout_location',
            field=models.CharField(choices=[('home', 'Home'), ('gym', 'Gym'), ('mixed', 'Mixed')], default='gym', verbose_name='Workout Location'),
        ),
    ]
