# Generated by Django 5.2.5 on 2025-08-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='weighthistory',
            name='notes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little/no exercise)'), ('lightly_active', 'Lightly Active (light exercise 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise 3-5 days/week)'), ('very_active', 'Very Active (hard exercise 6-7 days/week)')], max_length=20, verbose_name='Activity Level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_goal',
            field=models.CharField(choices=[('lose_weight', 'Lose Weight'), ('gain_weight', 'Gain Weight'), ('maintain_weight', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle'), ('build_strength', 'Build Strength')], max_length=20, verbose_name='Primary Body Goal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workout_location',
            field=models.CharField(choices=[('home', 'Home'), ('gym', 'Gym'), ('mixed', 'Mixed')], max_length=10, verbose_name='Preferred Workout Location'),
        ),
    ]
