# Generated by Django 5.2.4 on 2025-08-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_workout_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Current Weight'),
        ),
        migrations.AlterField(
            model_name='account',
            name='goal_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Goal Weight'),
        ),
    ]
