# Generated by Django 5.2.6 on 2025-10-20 08:30

import accounts.models.progress_photo
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_body_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_photo', models.ImageField(blank=True, help_text='Before photo showing initial state', null=True, upload_to=accounts.models.progress_photo.progress_photo_upload_path, validators=[accounts.models.progress_photo.validate_image_file_extension])),
                ('after_photo', models.ImageField(blank=True, help_text='After photo showing progress/results', null=True, upload_to=accounts.models.progress_photo.progress_photo_upload_path, validators=[accounts.models.progress_photo.validate_image_file_extension])),
                ('date_before', models.DateField(blank=True, help_text='Date when the before photo was taken', null=True)),
                ('date_after', models.DateField(blank=True, help_text='Date when the after photo was taken', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(help_text='The user who uploaded these progress photos', on_delete=django.db.models.deletion.CASCADE, related_name='progress_photo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Photo',
                'verbose_name_plural': 'Progress Photos',
            },
        ),
    ]
