# Generated by Django 5.2.5 on 2025-08-18 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_current_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active')], default=django.utils.timezone.now, verbose_name='Activity Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
