# Generated by Django 5.2.6 on 2025-12-09 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 9, 6, 22, 4, 511242, tzinfo=datetime.timezone.utc), help_text="User's date of birth", verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
