# Generated by Django 5.2.5 on 2025-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_templateexercise_remove_exercise_template_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateexercise',
            name='sets',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
