# Generated by Django 5.2.6 on 2025-10-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_template_isalternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='templateexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='templateexercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='sets_data',
            field=models.JSONField(blank=True, default=list, help_text='Array of objects containing reps and weight for each set'),
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='total_sets',
            field=models.IntegerField(default=1, help_text='Total number of sets'),
        ),
    ]
