from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404

from ..models.progress_report import ProgressReport, ProgressReportSettings
from ..serializers.progress_report import (
    ProgressReportSerializer,
    ProgressReportListSerializer,
    ProgressReportSettingsSerializer,
)


class ProgressReportViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for viewing progress reports.
    Reports are read-only as they're generated by background tasks.
    """

    permission_classes = [IsAuthenticated]
    serializer_class = ProgressReportSerializer

    def get_queryset(self):
        """Return progress reports for the authenticated user only"""
        return ProgressReport.objects.filter(user=self.request.user)

    def get_serializer_class(self):
        """Use list serializer for list action, detail serializer for retrieve"""
        if self.action == "list":
            return ProgressReportListSerializer
        return ProgressReportSerializer

    def list(self, request, *args, **kwargs):
        """List all progress reports for the user"""
        queryset = self.get_queryset()
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        """Get a specific progress report"""
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

    @action(detail=False, methods=["get"])
    def latest(self, request):
        """Get the most recent progress report"""
        latest_report = self.get_queryset().first()

        if not latest_report:
            return Response(
                {"detail": "No progress reports found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        serializer = self.get_serializer(latest_report)
        return Response(serializer.data)

    @action(detail=False, methods=["get"])
    def pending(self, request):
        """Get all pending progress reports"""
        pending_reports = self.get_queryset().filter(status="pending")
        serializer = ProgressReportListSerializer(pending_reports, many=True)
        return Response(serializer.data)


class ProgressReportSettingsViewSet(viewsets.ModelViewSet):
    """
    ViewSet for managing progress report settings.
    Users can view and update their report generation settings.
    """

    permission_classes = [IsAuthenticated]
    serializer_class = ProgressReportSettingsSerializer
    http_method_names = ["get", "put", "patch"]

    def get_queryset(self):
        """Return settings for the authenticated user only"""
        return ProgressReportSettings.objects.filter(user=self.request.user)

    def get_object(self):
        """Get or create settings for the authenticated user"""
        settings, created = ProgressReportSettings.objects.get_or_create(
            user=self.request.user
        )
        return settings

    def list(self, request, *args, **kwargs):
        """Get user's progress report settings"""
        settings = self.get_object()
        serializer = self.get_serializer(settings)
        return Response(serializer.data)

    def update(self, request, *args, **kwargs):
        """Update progress report settings"""
        partial = kwargs.pop("partial", False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def partial_update(self, request, *args, **kwargs):
        """Partially update progress report settings"""
        kwargs["partial"] = True
        return self.update(request, *args, **kwargs)

    @action(detail=False, methods=["post"])
    def toggle(self, request):
        """Toggle report generation on/off"""
        settings = self.get_object()
        settings.is_enabled = not settings.is_enabled
        settings.save()
        serializer = self.get_serializer(settings)
        return Response(serializer.data)
